/* generated by Svelte v4.2.5 */
import { create_ssr_component, escape, validate_component } from "svelte/internal";

import Component from './component.svelte';

const Component_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name = 'world' } = $$props;
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);

	return `<div>halo ${escape(name)}!
    <div>${validate_component(Component, "Component").$$render($$result, { name }, {}, {})}</div></div>`;
});

export default Component_1;